# Generated by Django 3.2.9 on 2021-11-30 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('translated_title', models.CharField(max_length=50)),
                ('core_gun', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[(1, 'Small - 1'), (2, 'Medium - 2'), (3, 'Large - 3')], max_length=10)),
                ('weight', models.FloatField()),
                ('price', models.IntegerField()),
                ('gun_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roulette.weapontype')),
            ],
        ),
    ]
