# Generated by Django 3.2.9 on 2021-11-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='sights',
            field=models.CharField(choices=[('ironsight', 'ironsight'), ('deadeye', 'deadeye'), ('marksman', 'marksman'), ('sniper', 'sniper'), ('aperture', 'aperture')], default='ironsight', max_length=50),
        ),
    ]
