# Generated by Django 3.2.9 on 2021-11-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_auto_20211130_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='melee',
            field=models.CharField(choices=[('talon', 'Talon'), ('hatchet', 'Hatchet'), ('bayonet', 'Bayonet'), ('mace', 'Mace'), ('none', 'None'), ('knukcles-duster', 'Knuckles')], default='None', max_length=50),
        ),
    ]
