# Generated by Django 3.2.9 on 2021-12-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0006_layout_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
