# Generated by Django 4.0 on 2021-12-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roulette', '0009_rename_gun_type_weapon_weapon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmmoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('double_clue', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_ammo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_weapon_ammo', to='stats.ammotype')),
                ('primary_weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_weapon', to='roulette.weapon')),
                ('secondary_ammo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_weapon_ammo', to='stats.ammotype')),
                ('secondary_weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_weapon', to='roulette.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('name', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills_count', models.IntegerField()),
                ('asissts_count', models.IntegerField()),
                ('deaths_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wl_status', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('kills_total', models.IntegerField(default=0)),
                ('playtime', models.DurationField()),
                ('player_1_kills', models.IntegerField(default=0)),
                ('player_2_kills', models.IntegerField(blank=True, default=0)),
                ('player_3_kills', models.IntegerField(blank=True, default=0)),
                ('fights_locations', models.ManyToManyField(to='stats.Compound', verbose_name='Place of a firefight')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1_name', to='stats.player')),
                ('player_1_kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1_equipment', to='stats.kit', verbose_name='Player eqipment')),
                ('player_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_name', to='stats.player')),
                ('player_2_kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2_equipment', to='stats.kit', verbose_name='Player eqipment')),
                ('player_3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_name', to='stats.player')),
                ('player_3_kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_3_equipment', to='stats.kit', verbose_name='Player eqipment')),
            ],
        ),
    ]
