# Generated by Django 4.0 on 2021-12-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='from_map',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='stats.map', verbose_name='Map'),
        ),
        migrations.AddField(
            model_name='compound',
            name='x_relative',
            field=models.FloatField(default=-2),
        ),
        migrations.AddField(
            model_name='compound',
            name='y_relative',
            field=models.FloatField(default=-2),
        ),
        migrations.AddField(
            model_name='kit',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='Sculptor', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2_name', to='stats.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_3_name', to='stats.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_kills',
            field=models.IntegerField(default=0),
        ),
    ]
