# Generated by Django 4.0 on 2021-12-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stats', '0002_compound_from_map_compound_x_relative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='also_known_as',
            field=models.CharField(blank=True, max_length=50, verbose_name='Also known as'),
        ),
        migrations.AddField(
            model_name='player',
            name='use_alternative_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='asissts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='deaths_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='kills_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.OneToOneField(on_delete=models.SET('Unknown player'), to='auth.user'),
        ),
    ]
