# Generated by Django 4.0 on 2021-12-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_player_also_known_as_player_use_alternative_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='primary_ammo',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='secondary_ammo',
        ),
        migrations.AddField(
            model_name='kit',
            name='primary_ammo_A',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='primary_weapon_ammo_A', to='stats.ammotype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kit',
            name='primary_ammo_B',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='primary_weapon_ammo_B', to='stats.ammotype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kit',
            name='secondary_ammo_A',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_weapon_ammo_A', to='stats.ammotype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kit',
            name='secondary_ammo_B',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_weapon_ammo_B', to='stats.ammotype'),
            preserve_default=False,
        ),
    ]
