# Generated by Django 4.0 on 2021-12-16 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_kit_primary_ammo_remove_kit_secondary_ammo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='primary_ammo_A',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='primary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='primary_ammo_B',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.PROTECT, related_name='primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='secondary_ammo_A',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='secondary_ammo_B',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
