# Generated by Django 4.0 on 2021-12-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_kit_primary_ammo_a_alter_kit_primary_ammo_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_1_kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_equipment', to='stats.kit', verbose_name='Player eqipment'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_name', to='stats.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_equipment', to='stats.kit', verbose_name='Player eqipment'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_name', to='stats.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_equipment', to='stats.kit', verbose_name='Player eqipment'),
        ),
    ]
