# Generated by Django 4.0 on 2021-12-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_match_player_1_kit_alter_match_player_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_name', to='stats.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_name', to='stats.player'),
        ),
    ]
