# Generated by Django 4.0 on 2021-12-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_match_player_2_alter_match_player_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_name', to='stats.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_equipment', to='stats.kit', verbose_name='Player eqipment'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_name', to='stats.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_equipment', to='stats.kit', verbose_name='Player eqipment'),
        ),
    ]
