# Generated by Django 4.0 on 2021-12-16 17:23

from django.db import migrations, models
import stats.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stats', '0008_alter_match_player_2_alter_match_player_2_kit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bounty',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator(input_type='bounty')], verbose_name='bounty'),
        ),
        migrations.AlterField(
            model_name='player',
            name='also_known_as',
            field=models.CharField(blank=True, max_length=50, validators=[stats.validators.UnicodeUsernameValidator()], verbose_name='Also known as'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.OneToOneField(on_delete=models.SET('Unknown player'), to='auth.user', validators=[stats.validators.UnicodeUsernameValidator()]),
        ),
    ]
