# Generated by Django 4.0 on 2021-12-18 08:43

from django.db import migrations, models
import stats.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_match_bounty_alter_player_also_known_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_1_assists',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('assists')]),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_deaths',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('deaths')]),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_assists',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('assists')]),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_deaths',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('deaths')]),
        ),
        migrations.AddField(
            model_name='match',
            name='player_3_assists',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('assists')]),
        ),
        migrations.AddField(
            model_name='match',
            name='player_3_deaths',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('deaths')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='bounty',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('bounty')], verbose_name='bounty'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_kills',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('kills')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_kills',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('kills')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_kills',
            field=models.IntegerField(default=0, validators=[stats.validators.NonNegativeValidator('kills')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='wl_status',
            field=models.FloatField(default=0, validators=[stats.validators.ListedValueValidator((0, 0.5, 1))]),
        ),
    ]
