# Generated by Django 4.0 on 2021-12-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0009_rename_gun_type_weapon_weapon_type'),
        ('stats', '0012_match_player_3_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player_1_kit',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_2_kit',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_3_kit',
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_primary_ammo_A',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_primary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_primary_ammo_B',
            field=models.ForeignKey(default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_primary_weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_primary_weapon', to='roulette.weapon'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_secondary_ammo_A',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_secondary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_secondary_ammo_B',
            field=models.ForeignKey(default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_secondary_weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_secondary_weapon', to='roulette.weapon'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_primary_ammo_A',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_primary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_primary_ammo_B',
            field=models.ForeignKey(default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_primary_weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_primary_weapon', to='roulette.weapon'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_secondary_ammo_A',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_secondary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_secondary_ammo_B',
            field=models.ForeignKey(default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_secondary_weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_secondary_weapon', to='roulette.weapon'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_3_primary_ammo_A',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_primary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_3_primary_ammo_B',
            field=models.ForeignKey(default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_3_primary_weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_primary_weapon', to='roulette.weapon'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_3_secondary_ammo_A',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_secondary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_3_secondary_ammo_B',
            field=models.ForeignKey(default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_3_secondary_weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_secondary_weapon', to='roulette.weapon'),
        ),
    ]
