# Generated by Django 4.0 on 2021-12-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0009_rename_gun_type_weapon_weapon_type'),
        ('stats', '0013_remove_match_player_1_kit_remove_match_player_2_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_1_primary_ammo_B',
            field=models.ForeignKey(blank=True, default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_secondary_ammo_B',
            field=models.ForeignKey(blank=True, default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_primary_ammo_A',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_primary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_primary_ammo_B',
            field=models.ForeignKey(blank=True, default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_primary_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_primary_weapon', to='roulette.weapon'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_secondary_ammo_A',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_secondary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_secondary_ammo_B',
            field=models.ForeignKey(blank=True, default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_secondary_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_secondary_weapon', to='roulette.weapon'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_primary_ammo_A',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_primary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_primary_ammo_B',
            field=models.ForeignKey(blank=True, default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_primary_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_primary_weapon', to='roulette.weapon'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_secondary_ammo_A',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_secondary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_secondary_ammo_B',
            field=models.ForeignKey(blank=True, default=19, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_secondary_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_secondary_weapon', to='roulette.weapon'),
        ),
    ]
