# Generated by Django 4.0 on 2021-12-18 18:34

from django.db import migrations, models
import stats.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stats', '0014_alter_match_player_1_primary_ammo_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.OneToOneField(on_delete=models.SET('Unknown player'), related_name='player_username', to='auth.user', validators=[stats.validators.UnicodeUsernameValidator()]),
        ),
    ]
