# Generated by Django 4.0 on 2021-12-18 19:25

from django.db import migrations, models
import django.db.models.deletion
import stats.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stats', '0015_alter_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='map_of_match', to='stats.map', verbose_name='Map of the match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.OneToOneField(on_delete=models.SET('Unknown player'), related_name='username_of_player', to='auth.user', validators=[stats.validators.UnicodeUsernameValidator()]),
        ),
    ]
