# Generated by Django 4.0 on 2021-12-24 13:24

from django.db import migrations, models
import stats.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stats', '0016_match_map_alter_player_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_2_assists',
            field=models.IntegerField(blank=True, default=0, validators=[stats.validators.NonNegativeValidator('assists')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_deaths',
            field=models.IntegerField(blank=True, default=0, validators=[stats.validators.NonNegativeValidator('deaths')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_kills',
            field=models.IntegerField(blank=True, default=0, validators=[stats.validators.NonNegativeValidator('kills')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_assists',
            field=models.IntegerField(blank=True, default=0, validators=[stats.validators.NonNegativeValidator('assists')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_deaths',
            field=models.IntegerField(blank=True, default=0, validators=[stats.validators.NonNegativeValidator('deaths')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_kills',
            field=models.IntegerField(blank=True, default=0, validators=[stats.validators.NonNegativeValidator('kills')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(6), related_name='username_of_player', to='auth.user', validators=[stats.validators.UnicodeUsernameValidator()]),
        ),
    ]
