# Generated by Django 4.0 on 2021-12-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_alter_match_player_2_assists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='asissts_count',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deaths_count',
        ),
        migrations.RemoveField(
            model_name='player',
            name='kills_count',
        ),
        migrations.AddField(
            model_name='match',
            name='correct_match',
            field=models.BooleanField(default=False, verbose_name='Match data is correct'),
        ),
    ]
