# Generated by Django 4.0 on 2021-12-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_player_allow_see_mathes_player_allow_see_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='see_only_my_matches',
            new_name='show_only_my_matches',
        ),
    ]
