# Generated by Django 4.0 on 2021-12-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_rename_see_only_my_matches_player_show_only_my_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='verified_user',
            field=models.BooleanField(default=False, verbose_name='Allow stats of this player be used in common statistics.'),
        ),
    ]
