# Generated by Django 4.0 on 2021-12-24 16:23

from django.db import migrations, models
import stats.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0021_player_verified_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='also_known_as',
            field=models.CharField(blank=True, max_length=50, validators=[stats.validators.UnicodeAndSpaceValidator()], verbose_name='Also known as'),
        ),
    ]
