# Generated by Django 4.0 on 2021-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0023_player_hash_key_player_hash_redeemable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(6), related_name='creator', to='stats.player', verbose_name="Showss who is the creator of this player. It's used only while player is not assigned to a user."),
        ),
    ]
