# Generated by Django 4.0 on 2021-12-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stats', '0024_player_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(6), related_name='creator', to='auth.user', verbose_name="Showss who is the creator of this player. It's used only while player is not assigned to a user."),
        ),
    ]
