# Generated by Django 4.0 on 2021-12-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0025_alter_player_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hash_redeemable',
            field=models.BooleanField(default=False, verbose_name='May be redeemed by a user'),
        ),
    ]
