# Generated by Django 4.0 on 2021-12-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0026_alter_player_hash_redeemable'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='may_be_duplicate',
            field=models.BooleanField(default=False, verbose_name='Allows this player to have duplicate in match. Service field.'),
        ),
    ]
