# Generated by Django 4.0.2 on 2022-02-14 11:39

from django.db import migrations, models
import stats.validators


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0027_player_may_be_duplicate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bounty',
        ),
        migrations.AddField(
            model_name='match',
            name='player_1_bounty',
            field=models.IntegerField(blank=True, default=0, validators=[stats.validators.NonNegativeValidator('bounty')], verbose_name='player 1 bounty'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_bounty',
            field=models.IntegerField(blank=True, default=0, validators=[stats.validators.NonNegativeValidator('bounty')], verbose_name='player 2 bounty'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_3_bounty',
            field=models.IntegerField(blank=True, default=0, validators=[stats.validators.NonNegativeValidator('bounty')], verbose_name='player 3 bounty'),
        ),
    ]
