# Generated by Django 4.0.3 on 2022-03-22 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stats.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0029_match_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_1_primary_ammo_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_primary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_primary_ammo_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_secondary_ammo_A',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_secondary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_secondary_ammo_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_1_secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_primary_ammo_A',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_primary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_primary_ammo_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_secondary_ammo_A',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_secondary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_secondary_ammo_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_2_secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_primary_ammo_A',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_primary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_primary_ammo_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_primary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_secondary_ammo_A',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_secondary_weapon_ammo_A', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_3_secondary_ammo_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_3_secondary_weapon_ammo_B', to='stats.ammotype'),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(2), related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name="Showss who is the creator of this player. It's used only while player is not assigned to a user."),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(2), related_name='username_of_player', to=settings.AUTH_USER_MODEL, validators=[stats.validators.UnicodeUsernameValidator()]),
        ),
        migrations.DeleteModel(
            name='Kit',
        ),
    ]
