"""core tables

Revision ID: 23c41f647b1e
Revises:
Create Date: 2025-10-20 19:56:10.473792

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23c41f647b1e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ammo_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ammo_types")),
    )
    op.create_table(
        "maps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maps")),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_table(
        "weapon_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weapon_types")),
        sa.UniqueConstraint("name", name=op.f("uq_weapon_types_name")),
    )
    op.create_table(
        "compounds",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("map_id", sa.Integer(), nullable=False),
        sa.Column("double_clue", sa.Boolean(), nullable=False),
        sa.Column("x_relative", sa.Float(), nullable=False),
        sa.Column("y_relative", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["map_id"],
            ["maps.id"],
            name=op.f("fk_compounds_map_id_maps"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_compounds")),
    )
    op.create_table(
        "weapons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("weapon_type_id", sa.Integer(), nullable=False),
        sa.Column("core_gun_id", sa.Integer(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sights", sa.String(length=50), nullable=False),
        sa.Column("melee", sa.String(length=50), nullable=False),
        sa.Column("muzzle", sa.String(length=50), nullable=False),
        sa.Column("magazine", sa.String(length=50), nullable=False),
        sa.Column("ammo_size", sa.String(length=50), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("has_ammo_B", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["core_gun_id"],
            ["weapons.id"],
            name=op.f("fk_weapons_core_gun_id_weapons"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["weapon_type_id"],
            ["weapon_types.id"],
            name=op.f("fk_weapons_weapon_type_id_weapon_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weapons")),
        sa.UniqueConstraint("name", name=op.f("uq_weapons_name")),
    )
    op.create_table(
        "match_player_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("primary_weapon_id", sa.Integer(), nullable=True),
        sa.Column("primary_ammo_A_id", sa.Integer(), nullable=True),
        sa.Column("primary_ammo_B_id", sa.Integer(), nullable=True),
        sa.Column("secondary_weapon_id", sa.Integer(), nullable=True),
        sa.Column("secondary_ammo_A_id", sa.Integer(), nullable=True),
        sa.Column("secondary_ammo_B_id", sa.Integer(), nullable=True),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("deaths", sa.Integer(), nullable=False),
        sa.Column("bounty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_match_player_data_player_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["primary_ammo_A_id"],
            ["ammo_types.id"],
            name=op.f("fk_match_player_data_primary_ammo_A_id_ammo_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["primary_ammo_B_id"],
            ["ammo_types.id"],
            name=op.f("fk_match_player_data_primary_ammo_B_id_ammo_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["primary_weapon_id"],
            ["weapons.id"],
            name=op.f("fk_match_player_data_primary_weapon_id_weapons"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["secondary_ammo_A_id"],
            ["ammo_types.id"],
            name=op.f("fk_match_player_data_secondary_ammo_A_id_ammo_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["secondary_ammo_B_id"],
            ["ammo_types.id"],
            name=op.f("fk_match_player_data_secondary_ammo_B_id_ammo_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["secondary_weapon_id"],
            ["weapons.id"],
            name=op.f("fk_match_player_data_secondary_weapon_id_weapons"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_player_data")),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wl_status", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("kills_total", sa.Integer(), nullable=False),
        sa.Column("playtime", sa.Interval(), nullable=False),
        sa.Column("map_name", sa.Integer(), nullable=True),
        sa.Column("player_1_id", sa.Integer(), nullable=False),
        sa.Column("player_1_match_data", sa.Integer(), nullable=False),
        sa.Column("player_2_id", sa.Integer(), nullable=True),
        sa.Column("player_2_match_data", sa.Integer(), nullable=False),
        sa.Column("player_3_id", sa.Integer(), nullable=True),
        sa.Column("player_3_match_data", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["map_name"],
            ["maps.id"],
            name=op.f("fk_matches_map_name_maps"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_1_id"],
            ["players.id"],
            name=op.f("fk_matches_player_1_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_1_match_data"],
            ["match_player_data.id"],
            name=op.f("fk_matches_player_1_match_data_match_player_data"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_2_id"],
            ["players.id"],
            name=op.f("fk_matches_player_2_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_2_match_data"],
            ["match_player_data.id"],
            name=op.f("fk_matches_player_2_match_data_match_player_data"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_3_id"],
            ["players.id"],
            name=op.f("fk_matches_player_3_id_players"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["player_3_match_data"],
            ["match_player_data.id"],
            name=op.f("fk_matches_player_3_match_data_match_player_data"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matches")
    op.drop_table("match_player_data")
    op.drop_table("weapons")
    op.drop_table("compounds")
    op.drop_table("weapon_types")
    op.drop_table("players")
    op.drop_table("maps")
    op.drop_table("ammo_types")
    # ### end Alembic commands ###
