"""id to compound and map

Revision ID: 074c8bff35b7
Revises: 23c41f647b1e
Create Date: 2025-10-21 11:47:41.322489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '074c8bff35b7'
down_revision: Union[str, None] = '23c41f647b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compounds', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('compounds', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.create_unique_constraint('unique_compound_per_map', 'compounds', ['map_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_compound_per_map', 'compounds', type_='unique')
    op.alter_column('compounds', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('compounds', 'id')
    # ### end Alembic commands ###
