"""weaponsize column

Revision ID: 54608ca4434b
Revises: 074c8bff35b7
Create Date: 2025-10-22 08:30:07.685019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import models.enums.weapon_modifiers as mod

# revision identifiers, used by Alembic.
revision: str = "54608ca4434b"
down_revision: Union[str, None] = "074c8bff35b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("weapons", "size", new_column_name="slot_size")
    op.add_column(
        "weapons", sa.Column("weapon_size", sa.String(length=50), nullable=True)
    )
    op.execute(
        f"""
            UPDATE weapons 
            SET weapon_size = '{mod.WeaponSizeEnum.REGULAR}' 
            WHERE weapon_size IS NULL;
        """
    )
    op.alter_column("weapons", "weapon_size", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weapons", "weapon_size")
    op.alter_column("weapons", "slot_size", new_column_name="size")
    # ### end Alembic commands ###
