"""player_status

Revision ID: 2c68aa77e6c2
Revises: 393740b6ea4f
Create Date: 2025-10-31 08:16:05.461496

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c68aa77e6c2"
down_revision: Union[str, None] = "393740b6ea4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column("status", sa.String(), server_default="active", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "status")
    # ### end Alembic commands ###
