"""game_mode

Revision ID: dab925ee2bc8
Revises: 2c68aa77e6c2
Create Date: 2026-01-17 19:26:21.333230

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dab925ee2bc8"
down_revision: Union[str, None] = "2c68aa77e6c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column("game_mode", sa.String(), server_default="hunt", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "game_mode")
    # ### end Alembic commands ###
