# Generated by Django 3.2.9 on 2021-11-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0002_weapon_sights'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='melee',
            field=models.CharField(choices=[('ironsight', 'ironsight'), ('deadeye', 'deadeye'), ('marksman', 'marksman'), ('sniper', 'sniper'), ('aperture', 'aperture')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='weapon',
            name='muzzle',
            field=models.CharField(choices=[('None', 'None'), ('silencer', 'Silencer')], default='None', max_length=50),
        ),
    ]
