# Generated by Django 3.2.9 on 2021-11-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0004_alter_weapon_melee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='translated_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
