# Generated by Django 3.2.9 on 2021-12-05 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0005_alter_weapon_translated_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_size', models.IntegerField()),
                ('secondary_size', models.IntegerField()),
                ('quartermeister_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(default=1)),
                ('layout_type', models.ForeignKey(default='3+1', on_delete=django.db.models.deletion.PROTECT, to='roulette.slots')),
                ('primary_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_weapon_type', to='roulette.weapontype')),
                ('secondary_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_weapon_type', to='roulette.weapontype')),
            ],
        ),
    ]
