# Generated by Django 3.2.9 on 2021-12-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0008_rename_chance_layout_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='gun_type',
            new_name='weapon_type',
        ),
    ]
