# Generated by Django 4.0 on 2021-12-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0009_rename_gun_type_weapon_weapon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='is_ammo_B',
            field=models.BooleanField(default=False, verbose_name='Does this weapon have 2nd ammo type?'),
        ),
    ]
